name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  it_is_job:
    runs-on: ubuntu-20.04
    steps:
      - name: It is
        run: |
          echo date
